language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js: '8'

stages:
  - name: test + lint
  - name: test-with-coverage
    if: (NOT (type = pull_request ))
  - security-tests
  - name: deploy
    if: (NOT (type = pull_request ))

install:
  - yarn install

before_script:
  - yarn run build-css

jobs:
  include:
    - stage: test + lint
      script: yarn lint
    - script: yarn test
    - stage: test-with-coverage
      script: yarn test-coverage
    - stage: security-tests
      install: skip
      before_script: skip
      services:
        - docker
      script: bash ci/security-checks.sh
    - stage: deploy
      before_script:
        - yarn build
      deploy:
        provider: firebase
        skip_cleanup: true
        on:
          branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a387d084c573fd34e585
    on_success: change
    on_failure: always
    on_start: always
